data work.work;
	set sassym.alldata_2000_2016_halfmissing;
	rename gdp__constant_2010_us__ = GDP;
	rename gdp_growth__annual___ = GDPGrowth;
	rename gdp_per_capita__constant_2010_US = GDPPerCap;
	rename gdp_per_capita_growth__annual___ = GDPPErCapGrowth;
run;

data work.work2;
	set work.work;
	by countryname year;
	GDPPerCap_Lag1 = LAG(GDPPerCap);
	GDPPerCap_Lag5 = LAG5(GDPPerCap);
	IF first.country THEN DO;
		GDPPerCap_Lag1 = .;
		GDPPerCap_Lag5 = .;
	END; 
run;	

data work.work2;
	set work.work;
	by countryname year;
	
	/* Creating Percent Change Variables */
	SP_DYN_CBRT_IN_Change = DIF(SP_DYN_CBRT_IN)/LAG(SP_DYN_CBRT_IN);
	EN_POP_DNST_Change = DIF(EN_POP_DNST)/LAG(EN_POP_DNST);
	NE_TRD_GNFS_ZS_Change = DIF(NE_TRD_GNFS_ZS)/LAG(NE_TRD_GNFS_ZS);
	SE_SEC_ENRR_Change = DIF(SE_SEC_ENRR)/LAG(SE_SEC_ENRR);
	SL_TLF_CACT_FE_NE_ZS_Change = DIF(SL_TLF_CACT_FE_NE_ZS)/LAG(SL_TLF_CACT_FE_NE_ZS);
	SP_DYN_LE00_IN_Change =DIF(SP_DYN_LE00_IN)/LAG(SP_DYN_LE00_IN);
	SP_DYN_TO65_FE_ZS_Change = DIF(SP_DYN_TO65_FE_ZS)/LAG(SP_DYN_TO65_FE_ZS);
	SP_DYN_TO65_MA_ZS_Change = DIF(SP_DYN_TO65_MA_ZS)/LAG(SP_DYN_TO65_MA_ZS);
	TM_TAX_MANF_WM_AR_ZS_Change = DIF(TM_TAX_MANF_WM_AR_ZS)/LAG(TM_TAX_MANF_WM_AR_ZS);
	NetEF_Change = DIF(NetEF);
	NetEF_PercChange = DIF(NetEF)/LAG(NetEF);
	
	IF first.countryname then do;
		SP_DYN_CBRT_IN_Change = .;
		EN_POP_DNST_Change = .;
		NE_TRD_GNFS_ZS_Change = .;
		SE_SEC_ENRR_Change = .;
		SL_TLF_CACT_FE_NE_ZS_Change = .;
		SP_DYN_LE00_IN_Change = .;
		SP_DYN_TO65_FE_ZS_Change = .;
		SP_DYN_TO65_MA_ZS_Change = .;
		TM_TAX_MANF_WM_AR_ZS_Change = .;
		NetEF_Change = .;
		NetEF_PercChange = .;
	END;
	
	/* Creating lag variabels of Percent Change Variables. So What was the year or over year
		percent change from 1,3,5,10 years ago? */
	SP_DYN_CBRT_IN_Change_Lag1 = LAG(SP_DYN_CBRT_IN_Change);
	SP_DYN_CBRT_IN_Change_Lag3 = LAG3(SP_DYN_CBRT_IN_Change);
	SP_DYN_CBRT_IN_Change_Lag5 = LAG5(SP_DYN_CBRT_IN_Change);
	SP_DYN_CBRT_IN_Change_Lag10 = LAG10(SP_DYN_CBRT_IN_Change);
	EN_POP_DNST_Change_Lag1 = LAG(EN_POP_DNST_Change);
	EN_POP_DNST_Change_Lag3 = LAG3(EN_POP_DNST_Change);
	EN_POP_DNST_Change_Lag5 = LAG5(EN_POP_DNST_Change);
	EN_POP_DNST_Change_Lag10 = LAG10(EN_POP_DNST_Change);
	NE_TRD_GNFS_ZS_Change_Lag1 = LAG(NE_TRD_GNFS_ZS_Change);
	NE_TRD_GNFS_ZS_Change_Lag3 = LAG3(NE_TRD_GNFS_ZS_Change);
	NE_TRD_GNFS_ZS_Change_Lag5 = LAG5(NE_TRD_GNFS_ZS_Change);
	NE_TRD_GNFS_ZS_Change_Lag10 = LAG10(NE_TRD_GNFS_ZS_Change);
	SE_SEC_ENRR_Change_Lag1 = LAG(SE_SEC_ENRR_Change);
	SE_SEC_ENRR_Change_Lag3 = LAG3(SE_SEC_ENRR_Change);
	SE_SEC_ENRR_Change_Lag5 = LAG5(SE_SEC_ENRR_Change);
	SE_SEC_ENRR_Change_Lag10 = LAG10(SE_SEC_ENRR_Change);
	SL_TLF_CACT_FE_NE_Change_Lag1 = LAG(SL_TLF_CACT_FE_NE_ZS_Change);
	SL_TLF_CACT_FE_NE_Change_Lag3 = LAG3(SL_TLF_CACT_FE_NE_ZS_Change);
	SL_TLF_CACT_FE_NE_Change_Lag5 = LAG5(SL_TLF_CACT_FE_NE_ZS_Change);
	SL_TLF_CACT_FE_NE_Change_Lag10 = LAG10(SL_TLF_CACT_FE_NE_ZS_Change);
	SP_DYN_LE00_IN_Change_Lag1 = LAG(SP_DYN_LE00_IN_Change);
	SP_DYN_LE00_IN_Change_Lag3 = LAG3(SP_DYN_LE00_IN_Change);
	SP_DYN_LE00_IN_Change_Lag5 = LAG5(SP_DYN_LE00_IN_Change);
	SP_DYN_LE00_IN_Change_Lag10 = LAG10(SP_DYN_LE00_IN_Change);
	SP_DYN_TO65_FE_ZS_Change_Lag1 = Lag(SP_DYN_TO65_FE_ZS_Change);
	SP_DYN_TO65_FE_ZS_Change_Lag3 = Lag3(SP_DYN_TO65_FE_ZS_Change);
	SP_DYN_TO65_FE_ZS_Change_Lag5 = Lag5(SP_DYN_TO65_FE_ZS_Change);
	SP_DYN_TO65_FE_ZS_Change_Lag10 = Lag10(SP_DYN_TO65_FE_ZS_Change);
	SP_DYN_TO65_MA_ZS_Change_Lag1 = LAG(SP_DYN_TO65_MA_ZS_Change);
	SP_DYN_TO65_MA_ZS_Change_Lag3 = LAG3(SP_DYN_TO65_MA_ZS_Change);
	SP_DYN_TO65_MA_ZS_Change_Lag5 = LAG5(SP_DYN_TO65_MA_ZS_Change);
	SP_DYN_TO65_MA_ZS_Change_Lag10 = LAG10(SP_DYN_TO65_MA_ZS_Change);
	TM_TAX_MANF_WM_AR_ZS_Change_Lag1 = LAG(TM_TAX_MANF_WM_AR_ZS_Change);
	TM_TAX_MANF_WM_AR_ZS_Change_Lag3 = LAG3(TM_TAX_MANF_WM_AR_ZS_Change);
	TM_TAX_MANF_WM_AR_ZS_Change_Lag5 = LAG5(TM_TAX_MANF_WM_AR_ZS_Change);
	TM_TAX_MANF_WM_AR_ZS_Change_Lag7 = LAG10(TM_TAX_MANF_WM_AR_ZS_Change);
	
	IF first.countryname then do;
		SP_DYN_CBRT_IN_Change_Lag1 = .;
		SP_DYN_CBRT_IN_Change_Lag3 = .;
		SP_DYN_CBRT_IN_Change_Lag5 = .;
		SP_DYN_CBRT_IN_Change_Lag10 = .;
		EN_POP_DNST_Change_Lag1 = .;
		EN_POP_DNST_Change_Lag3 = .;
		EN_POP_DNST_Change_Lag5 = .;
		EN_POP_DNST_Change_Lag10 = .;
		NE_TRD_GNFS_ZS_Change_Lag1 = .;
		NE_TRD_GNFS_ZS_Change_Lag3 = .;
		NE_TRD_GNFS_ZS_Change_Lag5 = .;
		NE_TRD_GNFS_ZS_Change_Lag10 = .;
		SE_SEC_ENRR_Change_Lag1 = .;
		SE_SEC_ENRR_Change_Lag3 = .;
		SE_SEC_ENRR_Change_Lag5 = .;
		SE_SEC_ENRR_Change_Lag10 = .;
		SL_TLF_CACT_FE_NE_Change_Lag1 = .;
		SL_TLF_CACT_FE_NE_Change_Lag3 = .;
		SL_TLF_CACT_FE_NE_Change_Lag5 = .;
		SL_TLF_CACT_FE_NE_Change_Lag10 = .;
		SP_DYN_LE00_IN_Change_Lag1 = .;
		SP_DYN_LE00_IN_Change_Lag3 = .;
		SP_DYN_LE00_IN_Change_Lag5 = .;
		SP_DYN_LE00_IN_Change_Lag10 = .;
		SP_DYN_TO65_FE_ZS_Change_Lag1 = .;
		SP_DYN_TO65_FE_ZS_Change_Lag3 = .;
		SP_DYN_TO65_FE_ZS_Change_Lag5 = .;
		SP_DYN_TO65_FE_ZS_Change_Lag10 = .;
		SP_DYN_TO65_MA_ZS_Change_Lag1 = .;
		SP_DYN_TO65_MA_ZS_Change_Lag3 = .;
		SP_DYN_TO65_MA_ZS_Change_Lag5 = .;
		SP_DYN_TO65_MA_ZS_Change_Lag10 = .;
		TM_TAX_MANF_WM_AR_ZS_Change_Lag1 = .;
		TM_TAX_MANF_WM_AR_ZS_Change_Lag3 = .;
		TM_TAX_MANF_WM_AR_ZS_Change_Lag5 = .;
		TM_TAX_MANF_WM_AR_ZS_Change_Lag7 = .;
	END;
Run;

data work.work2;
	set work.work2;
	if year = '2015' or year='2016' then TrainSet = 1;
	Else TrainSet = 0;
run;	